### ISSUE TITLE
Social Media icons hover effect broken in dark mode

### ISSUE THREAD

**Issue by realansgar** [526avijitgupta/gokarna#104]
This fix #81 unfortunately breaks the hover effect of social media icons in dark mode. Hovering over the social icons only shows the accent color for a short time (the transition time) and then the icon is white again. This is because of CSS selector precedence: `a:hover { fill: var(--accent-color); }` in `main.css` takes less precedence than `.social-icons-list .social-icon a:visited { fill: var(--dark-text-color); }` because the latter is more specific. To fix this, we need to add a selector with the same specificity that applies the hover effect again. In `dark.css`, add:
```css
.social-icons-list .social-icon a:hover {
  fill: var(--accent-color);
}
```
