### ISSUE TITLE
Tag links do not work when baseURL has a path prefix

### ISSUE THREAD

**Issue by dchiquito** [526avijitgupta/gokarna#126]
My site is deployed at `https://my.domain.com/blog/`, rather than the more traditional `https://my.domain.com`. The tag links that appear under post titles incorrectly omit the `/blog/` prefix, instead linking to `https://my.domain.com/tags/whatever`.

I solved this by adding my own `post.html` with this change:
```html
        <ul class="post-tags">
        {{ range .Params.tags }}
            <!-- old
            <li class="post-tag"><a href="{{ "/tags/" | absLangURL }}{{ . | urlize }}">{{ . }}</a></li>
            -->
            <!-- new, prefixed / from "/tags/" removed -->
            <li class="post-tag"><a href="{{ "tags/" | absLangURL }}{{ . | urlize }}">{{ . }}</a></li>
        {{ end }}
        </ul>
```
Interestingly, the `Tags` link from the nav header works correctly, even though I set it's URL to `/tags/` in `config.toml`:
```toml
  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 4
```
