### ISSUE TITLE
Injecting SVG is dark

### ISSUE THREAD

**Issue by lzap** [526avijitgupta/gokarna#139]
Hey, thanks for the template! It is great.

I am trying to inject Mastodon icon in the main menu:

```
  [[menu.main]]
  identifier = "mastodon"
  pre = "<img class='svg-inject' src='/svg/icons/mastodon.svg' />"
  url = "https://social.zapletalovi.com/@lukas"
  weight = 4
```

But for some reason it loads dark:

<img width="386" alt="Snímek obrazovky 2022-11-10 v 12 28 21" src="https://user-images.githubusercontent.com/49752/201079767-210084b7-63f2-4a10-97b9-de2f22c8f1aa.png">

It renders fine on the front page (social icons). When I flip dark/light mode everything flips correctly, except this mastodon icon (the same icon on the social section does flip correctly).

Any idea what is wrong? I am not good in CSS stuff, no idea.

FYI the documentation is missing the `/svg` prefix, so I added it.

**Comment by dchiquito** [comment]
I just pasted your configuration into my blog and into the example site and both changed color correctly. The only thing I can think of would be some issue with the `hugo serve` live updates glitching, so perhaps restarting/rebuilding might solve the problem?

**Comment by lzap** [comment]
This is live, see here: https://lukas.zapletalovi.com

Now, you need to turn to dark mode, and then sometimes after when I returned to that page it started doing this. Not sure why.

**Comment by lzap** [comment]
Ok thanks, I was confused because it randomly worked.

**Comment by lzap** [comment]
For googlers: Feather icons project do not accept brand icons, therefore Mastodon is and will not be present.

If you still want to use feather icons but want to have any other SVG icon alongside in the main menu or anywhere else, just add it as SVG with "invert-me" class:

```toml
  [[menu.main]]
  identifier = "mastodon"
  # https://simpleicons.org (copy, paste, add width/height)
  pre = '<svg class="invert-me" role="img" height="20" width="20" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Mastodon</title><  path d="M23.268 5.313c-.35-2.578-2.617-4.61-5.304-5.004C17.51.242 15.792 0 11.813 0h-.03c-3.98 0-4.835.242-5.288.309C3.882.692 1.496 2.518.917   5.127.64 6.412.61 7.837.661 9.143c.074 1.874.088 3.745.26 5.611.118 1.24.325 2.47.62 3.68.55 2.237 2.777 4.098 4.96 4.857 2.336.792 4.849.923 7  .256.38.265-.061.527-.132.786-.213.585-.184 1.27-.39 1.774-.753a.057.057 0 0 0 .023-.043v-1.809a.052.052 0 0 0-.02-.041.053.053 0 0 0-.046-.01   20.282 20.282 0 0 1-4.709.545c-2.73 0-3.463-1.284-3.674-1.818a5.593 5.593 0 0 1-.319-1.433.053.053 0 0 1 .066-.054c1.517.363 3.072.546 4.632.54  6.376 0 .75 0 1.125-.01 1.57-.044 3.224-.124 4.768-.422.038-.008.077-.015.11-.024 2.435-.464 4.753-1.92 4.989-5.604.008-.145.03-1.52.03-1.67.00  2-.512.167-3.63-.024-5.545zm-3.748 9.195h-2.561V8.29c0-1.309-.55-1.976-1.67-1.976-1.23 0-1.846.79-1.846 2.35v3.403h-2.546V8.663c0-1.56-.617-2.3  5-1.848-2.35-1.112 0-1.668.668-1.67 1.977v6.218H4.822V8.102c0-1.31.337-2.35 1.011-3.12.696-.77 1.608-1.164 2.74-1.164 1.311 0 2.302.5 2.962 1.4  98l.638 1.06.638-1.06c.66-.999 1.65-1.498 2.96-1.498 1.13 0 2.043.395 2.74 1.164.675.77 1.012 1.81 1.012 3.12z"/></svg>'
  url = "https://mastodon.social/@lzap"
  weight = 50
```

And hack inverting into the `main.js` from the theme:

```js
      targets.forEach((target) => {
          target.querySelector('a').innerHTML = feather.icons[THEME_TO_ICON_CLASS[themeToSet].split('-')[1]].toSvg();
          target.querySelector("#dark-theme-toggle-screen-reader-target").textContent = [THEME_TO_ICON_TEXT_CLASS[themeToSet]];
          if (themeToSet === 'light') {
              document.querySelector(".invert-me").style.filter = ""
          } else {
              document.querySelector(".invert-me").style.filter = "invert(100%)"
          }
      });
```

This is an ugly hack, but it does the job for me. Cheers.

**Comment by paractmol** [comment]
The other solution would be to fix it with CSS.

In the main.css
```css
a:hover, .svg-inject:hover {
  color: var(--accent-color);
  fill: var(--accent-color);
}
```

And in the dark.css
```css
.svg-inject {
  fill: white;
}
```
