### ISSUE TITLE
Multi-langage

### ISSUE THREAD

**Issue by slallemand** [526avijitgupta/gokarna#257]
Hi,
Is there a way to switch from one langage to another ?
I would like to have a flag to switch easily for example.

Thanks

**Comment by jamesericdavidson** [comment]
These links may help; @pkierski has already contributed some `i8n` strings (#239, #240).

https://gohugo.io/content-management/multilingual/

https://gohugo.io/functions/lang/translate/

**Comment by slallemand** [comment]
In fact I was looking for a configuration option in the theme to automaticaly add shortcuts to translated content.
Finally, I just add a few entries in my menu configuration :

```yaml
    menu:
      main:
...
        - identifier: fr
          name: 🇫🇷
          url: /fr/
          weight: 4
        - identifier: en
          name: 🇬🇧
          url: /en/
          weight: 5
```
